<?php
declare (strict_types= 1) ;
// @codingStandardsIgnoreFile
/** @var $block \Aheadworks\Rbslider\Block\Banner */

use Aheadworks\Rbslider\Block\Banner ;
/** @var $escaper Magento\Framework\Escaper */
use Magento\Framework\Escaper ; 
/** @var ViewModelRegistry $viewModels */
$icons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class)
?>

<script>
    'use strict' ;
    function initAwRbslider(config){
        return {
            options: Object.assign({
            autoplay: true,
            pauseTimeBetweenTransitions: 3000,
            slideTransitionSpeed: 500,
            isStopAnimationMouseOnBanner: true,
            animation: 'fade',
            isRandomOrderImage: false,
            sliderListSelector: '.uk-slideshow',
            sliderItemSelector: '.aw-rbslider-item'
        } , config ),

        slideshow : {options:{}} ,
        /**
         * Initialize widget
         */
        initSlider(){
            // let self = this;

            /*if (self.options.isRandomOrderImage) {
                self._randomSort();
            }*/

            // window.addEventListener('initSlider.uk.component', (e, name, data) => {
            //     if (name === 'slideshow') {
            //         this.loadSlides(data);
            //     }
            // });
            this.slideshow = window.awRbslider(this.$el, {
                autoplay: this.options.autoplay,
                autoplayInterval: this.options.pauseTimeBetweenTransitions,
                duration: this.options.slideTransitionSpeed,
                pauseOnHover: this.options.isStopAnimationMouseOnBanner,
                animation: this.options.animation
            });

            this.loadSlides() ;
            // // Rewrite slideshow resize method
            this.slideshow.resize = () => this.resizeBanner(this.slideshow , this.$el) ;

            // Disable stop animation, if click on slide navigaton or dot navigation
            // this.element.on('click.uk.slideshow', '[data-uk-slideshow-item]', function(e) {
            //     if (this.slideshow.options.autoplay) {
            //         this.slideshow.start();
            //     }
            // });

            // Array.from(this.$el.querySelectorAll('[data-uk-slideshow-item]')).map(item => {
            //     item.addEventListener('click.uk.slideshow' , (e) => {
            //         if(slideshow.options.autoplay){
            //             slideshow.start() ;
            //         }
            //     }) ;
            // })


            // Slideshow paused, if mouse cursor on slide navigation or dot navigation
            // this.element.on({
            //     mouseenter: function() {
            //         if (slideshow.options.pauseOnHover) {
            //             slideshow.hovering = true;
            //         }
            //     },
            //     mouseleave: function() {
            //         slideshow.hovering = false;
            //     }
            // }, '.uk-dotnav, .uk-slidenav');

            // this.loadSlider() ;

            // const observer = new IntersectionObserver(entries => {
            //     if(entries[0].isIntersecting){
            //         this.loadSlider() ;
            //         observer.disconnect() ;
            //     }
            // }) ;
            // observer.observe(this.$el) ;

            // this.loadSlider() ;

            if (this.options.bannerSchedule.length > 0) {
                if (!this.timeValidator([this.options.bannerSchedule[0]])) {
                    this.delayedUpdate(this.options.bannerSchedule[0]);
                }
                if (this.timeValidator(this.options.bannerSchedule)) {
                    this.sendRequest(this.options.bannerId);
                }
            }
            window.loadSlider = () => this.loadSlider() ;
        },

        loadSlider(){
            if(!window.awRbslider){
                let callbacks = [] ; 
                window.awRbslider = {'-isloading' : (callback)=> callbacks.push(callback) } ;
                // setTimeout(() =>{
                    // } , 3000) ;
                const script = document.createElement('script') ;
                script.src = '<?= $escaper->escapeJs($block->getViewFileUrl('Humcommerce_HyvaAheadworks/js/components/slideshow.js')) ?>'
                script.onload = () => {
                    callbacks.map(callback => callback()) ;
                    callbacks = [] ;
                }
                document.head.append(script) ;
            }
            if(window.awRbslider['-isloading']){
                window.awRbslider['-isloading'](()=> this.loadSlider()) ;
            }
            if(!window.awRbslider['-isloading']){
                // console.log('Instantiate slider here') ; 
                this.initSlider() ; 
            }
        },

        pauseOnEnter(){
            if (this.slideshow.options.pauseOnHover) {
                    this.slideshow.hovering = true;
                }
        } , 
        resumeOnLeave(){
            this.slideshow.hovering = false;
        },

        /**
         * Recalculate the width and height of the banner
         */
        resizeBanner(slideshow) {
            const mainContent = this.$el.closest('#maincontent, .page-wrapper');
            let width,
                height = slideshow.options.height;

            // Recalculate width
            if (slideshow.slides.length) {
                width = (slideshow.slides[0]).querySelector('img.aw-rbslider__img').naturalWidth;
            }
            if (mainContent) {
                if (mainContent.getBoundingClientRect().width < width) {
                    width = mainContent.getBoundingClientRect().width;
                }
                this.$el.style.width =  width + 'px' ;
            } 
            // Recalculate height
            if (slideshow.options.height === 'auto' && slideshow.slides.length) {
                slideshow.slides[0].style.height = '' ;
                height = (slideshow.slides[0]).getBoundingClientRect().height;
                slideshow.container.style.height = height + 'px';
                slideshow.slides.map(slide => {
                    slide.style.height = height + 'px' ;
                    slide.style.position = 'position' ;
                }) ;
                slideshow.slides.css('height', height);
                slideshow.slides.css('position', 'absolute');
            }
        },

        /**
         * Lazy load slides
         */
        loadSlides() {
            slideshow.slides.forEach((slideElem , index) => {
                if (index) {
                    const slideImg = (slideElem).querySelector('img.aw-rbslider__img');
                    if (slideImg && slideImg.dataset.src) {
                        slideImg.addEventListener('load' , ()=>{
                            slideImg.classList.add('is-loaded') ;
                        }) ;

                        slideImg.src =slideImg.dataset.src
                        slideImg.removeAttribute('data-src', null);
                    }
                }
            });
        },

        /**
         * Compare current time with schedule
         *
         * @param schedule
         */
        timeValidator(schedule) {
            const currentDateMinute = Math.floor(Date.now() / 1000 / 60) ;
            
            let isValid = false ;
            schedule.forEach((item) => {
                if (currentDate === new Math.floor(Date(item).getTime() / 1000 / 60 )) {
                    isValid = true;
                }
            });

            return isValid;
        },

        /**
         * Send request for clean banner cache
         *
         * @param bannerId
         */
        sendRequest(bannerId) {
            fetch(this.options.cacheCleanUrl, {
                method : 'post' ,
                headers : {
                    contentType : 'application/json'
                } ,
                body : JSON.stringify({bannerId}) 
            });
            // $.ajax({
            //     url: self.options.cacheCleanUrl,
            //     type: 'post',
            //     async: true,
            //     dataType: 'json',
            //     data: {
            //         'bannerId': bannerId
            //     }
            // });
        },

        /**
         * Calculate time before send ajax request
         *
         * @param futureTime
         */
        delayedUpdate(futureTime) {
            const currentDateMinute = Math.floor(Date.now() / 1000 / 60) ;
            const interval = (new Date(futureTime).getTime() / 1000 / 60 ) - currentDateMinute ;
            if (interval.valueOf() > 0) {
                setTimeout(() =>this.sendRequest(self.options.bannerId) , interval);
            }
        },

        /**
         * Random sort
         * @private
         */
        _randomSort: function () {
            const sliderListSelector = this.options.sliderListSelector,
                sliderItemSelector = this.options.sliderItemSelector;

            this.$el.querySelector(sliderListSelector)
                .innerHTML = Array.from(this.$el.querySelector(sliderListSelector + ' ' + sliderItemSelector))
                .sort(() => { Math.random()-0.5;})
                .map(item=> item.outerHTML)
                .join('') ;
            }
        };
    }
</script>

<?php if ($bannersBlock = $block->getBlocks()): ?>
    <?php foreach ($bannersBlock as $bannerBlock) : ?>
        <?php
            $dotNavItems = '';
            $slideCounter = 1;
            $sliderConfig = $block->getBannerMageInitParams($bannerBlock) ;
        ?>

     <?php /** $block->fetchview($block ->getTemplateFile("Humcommerce_HyvaAheadworks::animation/${transition}.phtml")) */ ?> 
        <div x-data='initAwRbslider(<?= /* @noEscape */ $block->jsonEncode($block->getBannerMageInitParams($bannerBlock)) ?>)'
            x-intersect = "loadSlider()" 
             data-aw-rbslider-banner-id='<?= /* @noEscape */ $bannerBlock->getBanner()->getId(); ?>'
             class="aw-rbslider-container uk-slidenav-position relative group">
            <div class="uk-slideshow uk-overlay-active">
                <?php foreach ($bannerBlock->getSlides() as $key => $slide) : ?>
                    <div class="aw-rbslider-item absolute" style="opacity: <?= $slideCounter === 1 ? '1' : '0' ?>">
                        <div class="aw-rbslider-img-wrapper">
                            <picture>
                                <source media="(max-width: 480px)" srcset="<?= /* @noEscape */ $block->getSlideMobileImgUrl($slide) ?>"
                                        class="aw-rbslider__img  <?= $slideCounter === 1 ? 'is-loaded' : '' ?>"
                                        <?= $slideCounter !== 1 ? 'data-' : '' ?>
                                        title="<?= $escaper->escapeHtml($slide->getImgTitle()) ?>" />
                                <img class="aw-rbslider__img  <?= $slideCounter === 1 ? 'is-loaded' : '' ?>"
                                     <?= $slideCounter !== 1 ? 'data-' : '' ?>src="<?= /* @noEscape */ $block->getSlideImgUrl($slide) ?>"
                                     title="<?= $escaper->escapeHtml($slide->getImgTitle()) ?>"
                                     alt="<?= $escaper->escapeHtml($slide->getImgAlt()) ?>" />
                            </picture>
                            <?php if ($slide->getUrl()): ?>
                                <?php
                                    $target = $slide->getIsOpenUrlInNewWindow() ? 'target="_blank"' : '';
                                    $nofollow = $slide->getIsAddNofollowToUrl() ? 'rel="nofollow"' : '';
                                ?>
                                <a href="<?= /* @noEscape */ $slide->getUrl() ?>"
                                   class="aw-rbslider-img-url"
                                   data-mage-initSlider='<?= /* @noEscape */ $block->jsonEncode($block->getSendClickStatisticsMageInitParams($bannerBlock->getBanner(), $slide)) ?>'
                                    <?= /* @noEscape */ $target ?>
                                    <?= /* @noEscape */ $nofollow ?>></a>
                            <?php endif; ?>
                            <?php if ($content = $slide->getContent()): ?>
                                <div class="aw-rbslider-content-wrapper uk-overlay-panel absolute top-0 w-full h-full flex justify-center items-center">
                                    <div class="prose">
                                        <?= /* @noEscape */ $content ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php $dotNavItems .= '<li data-uk-slideshow-item="' . $key . '"
                                            @click.prevent = "slideshow.show('. $key .')"
                                        ><a href="#" class="w-3 h-3 block bg-white mx-2 rounded-lg opacity-0 group:hover:opacity-50 hover:!opacity-80 transition-opacity duration-500" ></a></li>' ?>
                    <?php $slideCounter++; ?>
                    <!-- x-on:[click.uk.slideshow] ="slideshow.options.autoplay && slideshow.start()" -->
                <?php endforeach; ?>
            </div>
            <?php if (count($bannerBlock->getSlides()) > 1): ?>
            <div class="flex absolute top-0 text-white justify-between items-center w-full h-full">
                <?php if ($bannerBlock->getBanner()->getDisplayArrows()) : ?>
                    <a href="#"
                       class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous w-16 h-16 
                       opacity-0 group-hover:opacity-50 hover:!opacity-80 transition-opacity duration-500"
                       @mouseenter = "pauseOnEnter" @mouseleave = "resumeOnLeave"
                       @click.prevent = "slideshow.previous()"
                       data-uk-slideshow-item="previous">
                       <?= $icons->chevronLeftHtml('w-full h-full not-sr-only') ?>
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Show previous slide')) ?>
                        </span>
                    </a>
                <?php endif; ?>
                <?php if ($bannerBlock->getBanner()->getDisplayBullets()) : ?>
                    <ul class="uk-dotnav self-end mb-4"
                       @mouseenter = "pauseOnEnter" @mouseleave = "resumeOnLeave"
                       >
                        <?= /* @noEscape */  $dotNavItems ?>
                    </ul>
                <?php endif; ?>
                <?php if ($bannerBlock->getBanner()->getDisplayArrows()) : ?>
                    <a href="#"
                       class="uk-slidenav uk-slidenav-contrast uk-slidenav-next w-16 h-16 
                       opacity-0 group-hover:opacity-50 hover:!opacity-80 transition-opacity duration-500"
                       @mouseenter = "pauseOnEnter" @mouseleave = "resumeOnLeave"
                       @click.prevent = "slideshow.previous()"
                       data-uk-slideshow-item="next">
                       <?= $icons->chevronRightHtml ?>
                        <span class="sr-only">
                            <?= $escaper->escapeHtml(__('Show next slide')) ?>
                        </span>
                    </a>
                <?php endif; ?>
            </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
